- shell:
    - git submodule update --init --recursive
    - pip3 install --user pynvim
    - command: curl -sLf https://spacevim.org/install.sh | bash
      stdin: true
      stdout: true

- link:
    ~/.SpaceVim.d/init.toml: spacevim/init.toml
    ~/.SpaceVim.d/autoload/bootstrap.vim: spacevim/autoload/bootstrap.vim
