- link:
    ~/.ssh/config: ssh/config

- shell:
    - command: mkdir -p ~/.config/autostart
      description: "[ssh] Disable GNOME Keyring autostart (1/2)"

- shell:
    - command: echo "Hidden=true" > ~/.config/autostart/gnome-keyring-ssh.desktop
      description: "[ssh] Disable GNOME Keyring autostart (2/2)"
