# +------------+
# + Catppuccin +
# +------------+

# Fish shell

[".config/fish/themes/Catppuccin Frappe.theme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/fish/main/themes/Catppuccin%20Frappe.theme"
  refreshPeriod = "24h"

[".config/fish/themes/Catppuccin Latte.theme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/fish/main/themes/Catppuccin%20Latte.theme"
  refreshPeriod = "24h"

[".config/fish/themes/Catppuccin Macchiato.theme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/fish/main/themes/Catppuccin%20Macchiato.theme"
  refreshPeriod = "24h"

[".config/fish/themes/Catppuccin Mocha.theme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/fish/main/themes/Catppuccin%20Mocha.theme"
  refreshPeriod = "24h"

# GitKraken

[".gitkraken/themes/catppuccin-frappe.jsonc"]
  type = "file"
  url = "https://raw.githubusercontent.com/davi19/gitkraken/master/src/catppuccin-frappe.jsonc"
  refreshPeriod = "24h"

[".gitkraken/themes/catppuccin-latte.jsonc"]
  type = "file"
  url = "https://raw.githubusercontent.com/davi19/gitkraken/master/src/catppuccin-latte.jsonc"
  refreshPeriod = "24h"

[".gitkraken/themes/catppuccin-macchiato.jsonc"]
  type = "file"
  url = "https://raw.githubusercontent.com/davi19/gitkraken/master/src/catppuccin-macchiatto.jsonc"
  refreshPeriod = "24h"

[".gitkraken/themes/catppuccin-mocha.jsonc"]
  type = "file"
  url = "https://raw.githubusercontent.com/davi19/gitkraken/master/src/catppuccin-mocha.jsonc"
  refreshPeriod = "24h"

# bat

[".config/bat/themes/Catppuccin Latte.tmTheme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Latte.tmTheme"
  refreshPeriod = "24h"

[".config/bat/themes/Catppuccin Frappe.tmTheme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Frappe.tmTheme"
  refreshPeriod = "24h"

[".config/bat/themes/Catppuccin Macchiato.tmTheme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Macchiato.tmTheme"
  refreshPeriod = "24h"

[".config/bat/themes/Catppuccin Mocha.tmTheme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"
  refreshPeriod = "24h"

# delta

[".config/delta/themes/catppuccin.gitconfig"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/delta/main/catppuccin.gitconfig"
  refreshPeriod = "24h"
