tap "beeftornado/rmtree"
tap "github/gh"

brew "asdf"
brew "aws-iam-authenticator"
brew "awscli"
brew "diff-so-fancy"
brew "gh"
brew "helm"
brew "htop"
brew "neovim"
brew "pbzip2"
brew "pigz"
brew "shellcheck"

cask "font-iosevka"
cask "github"
cask "google-chrome"
cask "gpg-suite-no-mail"
cask "iterm2"
cask "mos"
cask "ngrok"
cask "postman"
cask "razer-synapse"
cask "slack"
cask "spotify"
cask "tunnelblick"
cask "visual-studio-code"
