tap "AdoptOpenJDK/openjdk"
tap "beeftornado/rmtree"
tap "homebrew/cask-fonts"
tap "homebrew/cask"

brew "hub"
brew "diff-so-fancy"
brew "htop"
brew "httpie"
brew "jq"
brew "nvim"
brew "nvm"
brew "pbzip2"
brew "pigz"
brew "shellcheck"
brew "watchman"

cask "adoptopenjdk8-openj9"
cask "android-studio"
cask "docker"
cask "fanny"
cask "font-iosevka"
cask "gitkraken"
cask "google-chrome"
cask "gpg-suite-no-mail"
cask "iterm2"
cask "kitematic"
cask "ngrok"
cask "postman"
cask "slack"
cask "tunnelblick"
cask "visual-studio-code"
cask "zeplin"

mas "Xcode", id: 497799835
