tap "AdoptOpenJDK/openjdk"
tap "beeftornado/rmtree"
tap "homebrew/cask-fonts"
tap "homebrew/cask"

brew "diff-so-fancy"
brew "ffmpeg"
brew "htop"
brew "httpie"
brew "nano"
brew "nvm"
brew "pbzip2"
brew "pigz"
brew "watchman"
brew "youtube-dl"
brew "zsh"

cask "alacritty"
cask "adoptopenjdk8-openj9"
cask "android-file-transfer"
cask "android-studio"
cask "blitz"
cask "discord"
cask "docker"
cask "fanny"
cask "font-iosevka"
cask "gitkraken"
cask "google-backup-and-sync"
cask "google-chrome"
cask "gpg-suite-no-mail"
cask "iina"
cask "iterm2"
cask "league-of-legends"
cask "minecraft"
cask "postman"
cask "slack"
cask "spotify"
cask "stremio"
cask "transmission"
cask "visual-studio-code"
cask "whatsapp"
cask "zeplin"

mas "Xcode", id: 497799835