#
# Macros
#
[macros.install_yarn_package]
  prefix = ["yarn", "global", "add"]

[macros.install_gem]
  prefix = ["gem", "install"]

#
# Pseudo-package tasks
#
[tasks.git]
  links = [
    ["${HM_DEST}/.czrc", "git/czrc"],
    ["${HM_DEST}/.git-commit-msg", "git/git-commit-msg"],
    ["${HM_DEST}/.gitconfig", "git/gitconfig"],
    ["${HM_DEST}/.gitignore", "git/gitignore"],
  ]

[tasks.htop]
  links = [["${HM_DEST}/.config/htop/htoprc", "htop/htoprc"]]

[tasks.ssh__darwin]
  links = [["${HM_DEST}/.ssh/config", "ssh/config"]]

[tasks.vscode__darwin]
  links = [
    ["${HM_DEST}/Library/Application Support/Code/User/snippets/markdown.json", "vscode/snippets/markdown.json"],
    ["${HM_DEST}/Library/Application Support/Code/User/settings.json", "vscode/settings.json"],
  ]

[tasks.zsh]
  links = [
    ["${HM_DEST}/.zimrc", "zsh/zimrc"],
    ["${HM_DEST}/.zlogin", "zsh/zlogin"],
    ["${HM_DEST}/.zlogout", "zsh/zlogout"],
    ["${HM_DEST}/.zshenv", "zsh/zshenv"],
    ["${HM_DEST}/.zshrc", "zsh/zshrc"],
    ["${HM_DEST}/.ztoken", "zsh/ztoken"],
  ]

#
# The father of all tasks.
# If you want your task to be executed, add it to the deps section.
#
[tasks.default__darwin]
  cmds = [
    ["sudo", "scutil", "--set", "HostName", "A1398"],
    ["sudo", "scutil", "--set", "LocalHostName", "A1398"],
    ["sudo", "scutil", "--set", "ComputerName", "A1398"],
    ["dscacheutil", "-flushcache"],
    ["@install_yarn_package", "commitizen", "cz-conventional-changelog"],
    ["@install_yarn_package", "lerna", "appcenter-cli", "react-native-cli"],
    ["@install_gem", "rails", "--no-document"],
    ["@install_gem", "bundler"],
    ["@install_gem", "cocoapods", "cocoapods-fix-react-native"],
  ]
  deps = [
    "git",
    "htop",
    "ssh",
    "vscode",
    "zsh",
  ]
  links = [
    ["${HM_DEST}/bin/colors", "bin/colors"],
    ["${HM_DEST}/bin/hls", "bin/hls"],
  ]

[tasks.default__linux]
  cmds = [
    ["@install_yarn_package", "commitizen", "cz-conventional-changelog"],
  ]
  deps = [
    "git",
    "htop",
    "zsh",
  ]
  links = [
    ["${HM_DEST}/bin/colors", "bin/colors"],
    ["${HM_DEST}/bin/hls", "bin/hls"],
  ]