#
# Macros
#
[macros.install_yarn_package]
  deps = ["install_yarn"]
  prefix = ["yarn", "global", "add"]

[macros.install_gem]
  deps = ["install_yarn"]
  prefix = ["sudo", "gem", "install"]

#
# Install tasks
#
[tasks.install_nodejs]
  rejects = [["which", "node"]]
  cmds = [["nvm", "install", "--lts"]]

[tasks.install_yarn]
  deps = ["install_nodejs"]
  rejects = [["which", "yarn"]]
  cmds = [["npm", "i", "-g", "yarn"]]

#
# Pseudo-package tasks
#
[tasks.git]
  links = [
    ["${HM_DEST}/.czrc", "git/czrc"],
    ["${HM_DEST}/.git-commit-msg", "git/git-commit-msg"],
    ["${HM_DEST}/.gitconfig", "git/gitconfig"],
  ]

[tasks.htop]
  links = [["${HM_DEST}/.config/htop/htoprc", "htop/htoprc"]]

[tasks.ssh]
  links = [["${HM_DEST}/.ssh/config", "ssh/config"]]

[tasks.zsh]
  # TODO: Remove after macOS 10.15 (Catalina) is out.
  cmds = [
    ["sudo", "dscl", ".", "-create", "/Users/$USER", "UserShell", "/usr/local/bin/zsh"]
  ]
  links = [
    ["${HM_DEST}/.zlogout", "zsh/zlogout"],
    ["${HM_DEST}/.zprofile", "zsh/zprofile"],
    ["${HM_DEST}/.zshenv", "zsh/zshenv"],
    ["${HM_DEST}/.zshrc", "zsh/zshrc"],
  ]

#
# The father of all tasks.
# If you want your task to be executed, add it to the deps section.
#
[tasks.default]
  cmds = [
    ["@install_yarn_package", "commitizen", "cz-conventional-changelog"],
    ["@install_yarn_package", "tldr"],
    ["@install_yarn_package", "lerna", "appcenter-cli", "react-native-cli"],
    ["@install_gem", "cocoapods", "-v 1.7.5"],
    ["@install_gem", "cocoapods-fix-react-native"],
  ]
  deps = [
    "git",
    "htop",
    "ssh",
    "zsh",
  ]
  links = [
    ["${HM_DEST}/bin/colors", "bin/colors"],
    ["${HM_DEST}/bin/open", "bin/open"],
    ["${HM_DEST}/bin/treed", "bin/treed"],
  ]