- defaults:
    link:
      create: true
      force: true
      relative: true

- clean: ["~", "~/.config"]

- link:
    ~/.config/bat/bat.conf: linux/bat/bat.conf
    ~/.config/fish/conf.d/00-environment.fish: linux/fish/conf.d/00-environment.fish
    ~/.config/fish/conf.d/01-fisher.fish: linux/fish/conf.d/01-fisher.fish
    ~/.config/fish/conf.d/02-keychain.fish: linux/fish/conf.d/02-keychain.fish
    ~/.config/fish/functions/diff.fish: linux/fish/functions/diff.fish
    ~/.config/fish/functions/fish_greeting.fish: linux/fish/functions/fish_greeting.fish
    ~/.config/fish/functions/fish_prompt.fish: linux/fish/functions/fish_prompt.fish
    ~/.config/fish/functions/grc.fish: linux/fish/functions/grc.fish
    ~/.config/fish/functions/magic_conch_shell.fish: linux/fish/functions/magic_conch_shell.fish
    ~/.config/fish/functions/mkd.fish: linux/fish/functions/mkd.fish
    ~/.config/fish/functions/mktempd.fish: linux/fish/functions/mktempd.fish
    ~/.config/fish/lib/nord-dircolors: linux/fish/lib/nord-dircolors
    ~/.config/fish/config.fish: linux/fish/config.fish
    ~/.config/fish/private.fish: linux/fish/private.fish
    ~/.config/git/commit_msg.txt: git/includes/templates/commit.txt
    ~/.config/git/user-rafifos.conf:
      if: '[ "$HOSTNAME" = GUARDIAN ]'
      path: git/includes/user-rafifos.conf
    ~/.config/git/user-mesalva.conf:
      if: '[ "$HOSTNAME" = drifter ]'
      path: git/includes/user-mesalva.conf
    ~/.config/htop/htoprc: linux/htop/htoprc
    ~/.config/neofetch/config.conf: linux/neofetch/config.conf
    ~/.config/nvim/init.vim: linux/nvim/init.vim
    ~/.config/procs/config.toml: linux/procs/config.toml
    ~/.gnupg/gpg-agent.conf: gnupg/gpg-agent.conf
    ~/.gnupg/gpg.conf: gnupg/gpg.conf
    ~/.gitattributes: git/attributes.conf
    ~/.gitconfig: git/config.conf
    ~/.gitignore: git/ignore.conf

- shell:
    - git submodule update --init --recursive
