#
# Macros
#
[macros.install_yarn_package]
  deps = ["install_yarn"]
  prefix = ["yarn", "global", "add"]

[macros.install_gem]
  prefix = ["sudo", "gem", "install"]

[macros.check_command]
  prefix = ["command", "-v"]
  suffix = [">/dev/null", "2>&1"]

#
# Install tasks
#
[tasks.install_nodejs]
  rejects = [["@check_command", "node"]]
  cmds = [["nvm", "install", "--lts"]]

[tasks.install_yarn]
  deps = ["install_nodejs"]
  rejects = [["@check_command", "yarn"]]
  cmds = [["npm", "i", "-g", "yarn"]]

#
# Pseudo-package tasks
#
[tasks.git]
  links = [
    ["${HM_DEST}/.czrc", "git/czrc"],
    ["${HM_DEST}/.git-commit-msg", "git/git-commit-msg"],
    ["${HM_DEST}/.gitconfig", "git/gitconfig"],
    ["${HM_DEST}/.gitignore", "git/gitignore"],
  ]

[tasks.htop]
  links = [["${HM_DEST}/.config/htop/htoprc", "htop/htoprc"]]

[tasks.ssh]
  links = [["${HM_DEST}/.ssh/config", "ssh/config"]]

[tasks.vscode]
  links = [
    ["${HM_DEST}/Library/Application Support/Code/User/snippets/markdown.json", "vscode/snippets/markdown.json"],
    ["${HM_DEST}/Library/Application Support/Code/User/settings.json", "vscode/settings.json"],
  ]

[tasks.zsh]
  cmds = [
    ["sudo", "dscl", ".", "-create", "/Users/$USER", "UserShell", "/usr/local/bin/zsh"]
  ]
  links = [
    ["${HM_DEST}/.zimrc", "zsh/zimrc"],
    ["${HM_DEST}/.zlogin", "zsh/zlogin"],
    ["${HM_DEST}/.zlogout", "zsh/zlogout"],
    ["${HM_DEST}/.zshenv", "zsh/zshenv"],
    ["${HM_DEST}/.zshrc", "zsh/zshrc"],
    ["${HM_DEST}/.ztoken", "zsh/ztoken"],
  ]

#
# The father of all tasks.
# If you want your task to be executed, add it to the deps section.
#
[tasks.default]
  cmds = [
    ["sudo", "scutil", "--set HostName", "A1398"],
    ["@install_yarn_package", "lerna", "appcenter-cli", "react-native-cli"],
    ["@install_yarn_package", "commitizen", "cz-conventional-changelog"],
    ["@install_gem", "cocoapods"],
    ["@install_gem", "cocoapods-fix-react-native"],
  ]
  deps = [
    "git",
    "htop",
    "ssh",
    "vscode",
    "zsh",
  ]
  links = [
    ["${HM_DEST}/bin/colors", "bin/colors"],
    ["${HM_DEST}/bin/hls", "bin/hls"],
  ]