#
# Pseudo-packages
#
[tasks.asdf]
links = [
  ["${HM_DEST}/.asdfrc", "asdf/asdfrc"],
  ["${HM_DEST}/.tool-versions", "asdf/tool-versions"],
  ["${HM_DEST}/.default-npm-packages", "asdf/nodejs/default-npm-packages"],
]

[tasks.git]
links = [
  ["${HM_DEST}/.git-commit-msg", "git/git-commit-msg"],
  ["${HM_DEST}/.gitconfig", "git/gitconfig"],
]

[tasks.htop]
links = [["${HM_DEST}/.config/htop/htoprc", "htop/htoprc"]]

[tasks.hyper]
links = [["${HM_DEST}/.hyper.js", "hyper/hyper.js"]]

[tasks.neofetch]
links = [["${HM_DEST}/.config/neofetch/config.conf", "neofetch/config.conf"]]

[tasks.nvim]
links = [["${HM_DEST}/.config/nvim/init.vim", "nvim/init.vim"]]

[tasks.zsh]
links = [
  ["${HM_DEST}/.p10k.zsh", "zsh/p10k.zsh"],
  ["${HM_DEST}/.zimrc", "zsh/zimrc"],
  ["${HM_DEST}/.zlogin", "zsh/zlogin"],
  ["${HM_DEST}/.zlogout", "zsh/zlogout"],
  ["${HM_DEST}/.zprivate", "zsh/zprivate"],
  ["${HM_DEST}/.zprofile", "zsh/zprofile"],
  ["${HM_DEST}/.zshenv", "zsh/zshenv"],
  ["${HM_DEST}/.zshrc", "zsh/zshrc"],
]

[tasks.default]
deps  = ["asdf", "git", "htop", "hyper", "nvim", "zsh"]
links = [
  ["${HM_DEST}/.local/bin/colors", "bin/colors"],
  ["${HM_DEST}/.local/bin/hls", "bin/hls"],
  ["${HM_DEST}/.local/bin/wslcmd", "bin/wslcmd"],
]
