- defaults:
    link:
      create: true
      force: true

- shell:
    - git submodule update --init --recursive
    - pip3 install --user pynvim
    - command: curl -sLf https://spacevim.org/install.sh | bash
      stdin: true
      stdout: true

- clean: ["~", "~/.config"]

- link:
    # GnuPG
    ~/.gnupg/gpg-agent.conf: gnupg/gpg-agent.conf
    ~/.gnupg/gpg.conf: gnupg/gpg.conf

    # git
    ~/.gitattributes: git/attributes.conf
    ~/.gitconfig: git/config.conf
    ~/.gitignore: git/ignore.conf
    ~/.config/git/commit_msg.txt: git/includes/templates/commit.txt
    ~/.config/git/user-rafifos.conf:
      if: '[ "$HOSTNAME" = GUARDIAN ]'
      path: git/includes/user-rafifos.conf
    ~/.config/git/user-mesalva.conf:
      if: '[ "$HOSTNAME" = drifter ]'
      path: git/includes/user-mesalva.conf

    # bat
    ~/.config/bat/bat.conf: bat/bat.conf

    # bottom
    ~/.config/bottom/bottom.toml: bottom/bottom.toml

    # lazydocker
    ~/.config/jesseduffield/lazydocker/config.yml: lazydocker/config.yml

    # asdf-vm
    ~/.asdfrc: asdf/asdfrc
    ~/.default-npm-packages: asdf/nodejs/default-npm-packages

    # SpaceVim
    ~/.SpaceVim.d/init.toml: spacevim/init.toml
    ~/.SpaceVim.d/autoload/bootstrap.vim: spacevim/autoload/bootstrap.vim

    # fish shell
    ~/.config/fish/conf.d/00-environment.fish: fish/conf.d/00-environment.fish
    ~/.config/fish/conf.d/01-fisher.fish: fish/conf.d/01-fisher.fish
    ~/.config/fish/conf.d/02-asdf.fish: fish/conf.d/02-asdf.fish
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/lib/nord-dircolors: fish/lib/nord-dircolors
    ~/.config/fish/functions/cat.fish: fish/functions/cat.fish
    ~/.config/fish/functions/diff.fish: fish/functions/diff.fish
    ~/.config/fish/functions/fish_greeting.fish: fish/functions/fish_greeting.fish
    ~/.config/fish/functions/fish_prompt.fish: fish/functions/fish_prompt.fish
    ~/.config/fish/functions/htop.fish: fish/functions/htop.fish
    ~/.config/fish/functions/ls.fish: fish/functions/ls.fish
    ~/.config/fish/functions/magic_conch_shell.fish: fish/functions/magic_conch_shell.fish
    ~/.config/fish/functions/mkd.fish: fish/functions/mkd.fish
    ~/.config/fish/functions/mktempd.fish: fish/functions/mktempd.fish
    ~/.config/fish/functions/npmup.fish: fish/functions/npmup.fish
    ~/.config/fish/functions/refreshenv.fish: fish/functions/refreshenv.fish
    ~/.config/fish/functions/rm.fish: fish/functions/rm.fish
    ~/.config/fish/private.fish: fish/private.fish
