#!/usr/bin/env bash

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIG_DIR="configs"
PLUGIN_DIR="plugins"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASE_DIR}"
git submodule update --init --recursive --remote

echo -e "\nInstall necessary dependency: yaml"
if command -v python3 &>/dev/null; then
  python3 -c "\
import pip

def import_or_install(package):
    try:
        __import__(package)
    except ImportError:
        pip.main(['install', package])

import_or_install('yaml')
"
else
  echo -e "\npython3 is not installed, please install it first."
  exit 1
fi

for config in "${@}"; do
  # create temporary file
  configFile="$(mktemp)"
  suffix="-sudo"
  echo -e "$(<"${BASE_DIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config%"$suffix"}${CONFIG_SUFFIX}")" >"$configFile"

  cmd=("${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir "${BASE_DIR}/${META_DIR}/${PLUGIN_DIR}/*" -c "$configFile")

  if [[ $config == *"sudo"* ]]; then
    cmd=(sudo "${cmd[@]}")
  fi

  echo "Execute: ${cmd[@]}"
  "${cmd[@]}"
  rm -f "$configFile"
done

cd "${BASE_DIR}"
