# Don't print a new line at the start of the prompt
add_newline = false

[battery]
  charging_symbol = "⚡ "
  discharging_symbol = "🔋"

# "bold red" style when capacity is between 0% and 10%
[[battery.display]]
  threshold = 10
  style = "bold red"

# "bold yellow" style when capacity is between 10% and 30%
[[battery.display]]
  threshold = 30
  style = "bold yellow"

[cmd_duration]
  min_time = 15

[hostname]
  ssh_only = false

[username]
  show_always = true