# ~/.zshenv: Sourced on ALL invocations of ZSH(1), unless the -f option is
# set.
#
# NOTE: It should NOT normally contain commands to set the command search path,
# or other common environment variables unless you really know what you're
# doing. E.g. running "PATH=/custom/path gdb program" sources this file (when
# gdb runs the program via $SHELL), so you want to be sure not to override a
# custom environment in such cases.  Note also that .zshenv should not contain
# commands that produce output or assume the shell is attached to a tty.
#

export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main pattern)
export ZSH_HIGHLIGHT_PATTERNS+=("rm *" "fg=white,bold,bg=red")

export ZSH_AUTOSUGGEST_USE_ASYNC=true

# Use nano as the default editor.
export EDITOR='nano'

# Colored GCC warnings and errors.
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

export NVM_DIR="$HOME/.nvm"

case "$OSTYPE" in
  darwin*)
    [[ -d "$HOME/Library/Android/sdk" ]] && export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
  ;;
  linux*)
    # TODO: Move Linux-only environment to this section.
  ;;
esac