# /etc/zsh/zshrc: system-wide .zshrc file for zsh(1).
#
# This file is sourced only for interactive shells. It
# should contain commands to set up aliases, functions,
# options, key bindings, etc.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

# Local plugins.
zinit load _local/config
zinit load _local/private
zinit load _local/exa
zinit load _local/fzf
zinit load _local/httpie
zinit load _local/rip
zinit load _local/ripgrep
zinit load _local/rsync

# An arctic, north-bluish clean and elegant dircolors theme.
zinit wait atclone'dircolors -b src/dir_colors > clrs.zsh' atpull'%atclone' \
  atload'_nord_dircolors_atload' pick'clrs.zsh' \
  nocompile'!' for arcticicestudio/nord-dircolors

# Enhances the terminal environment with 256 colors.
zinit wait for chrissicool/zsh-256color

# Colorize the output of various programs.
zinit wait for zpm-zsh/colorize

# oh-my-zsh.
# See: https://github.com/oh-my-zsh/oh-my-zsh
zinit wait for \
  OMZP::/cp \
  OMZP::/git-extras \
  OMZP::/httpie \
  OMZP::/rsync \
  OMZP::/safe-paste \
  as'completion' OMZ::plugins/adb/_adb \
  as'completion' OMZ::plugins/httpie/_httpie \
  as'completion' OMZ::plugins/yarn/_yarn

# This plugin doesn't work well with turbo mode.
zinit atinit'_omz_ssh_atinit' for OMZP::/ssh-agent

# Prezto
# See: https://github.com/sorin-ionescu/prezto
zinit wait for PZTM::command-not-found \
  as'null' svn atpull'zinit creinstall -q .' PZTM::archive

# A next-generation cd command with an interactive filter ✨
zinit wait atinit'_enhancd_atinit' for b4b4r07/enhancd

# Replace zsh's default completion selection menu with fzf!
zinit wait for Aloxaf/fzf-tab

# A tool designed to help you use git more efficiently.
zinit wait for wfxr/forgit

# Adds start, restart, stop, up and down commands when it detects a docker-compose or Vagrantfile in CWD.
zinit wait for Cloudstek/zsh-plugin-appup

# Clears previous command output every time before new command executed in shell.
zinit wait for Valiev/almostontop

# A zsh plugin that reminds you that you should use one of your existing aliases for a command you just typed.
zinit wait for MichaelAquilina/zsh-you-should-use

# docker and docker-compose completions.
zinit wait for greymd/docker-zsh-completion

# Better completion for npm.
zinit wait for lukechilds/zsh-better-npm-completion

# Additional completions for Zsh.
zinit wait blockf atpull'zinit creinstall -q .' for zsh-users/zsh-completions

# Loads completions bundled with the system.
zinit wait pack for system-completions

# Fish-like fast/unobtrusive autosuggestions for zsh.
zinit wait atload'_zsh_autosuggestions_atload' for zsh-users/zsh-autosuggestions

# 🐠 ZSH port of Fish history search (up arrow).
zinit wait atload'_zsh_history_substring_search_atload' \
  bindmap'UPAR -> history-substring-search-up; DOWNAR history-substring-search-down' \
  for zsh-users/zsh-history-substring-search

# Feature rich syntax highlighting for Zsh.
zinit wait atload'_zsh_syntax_highlighting_atload' for zsh-users/zsh-syntax-highlighting

# A plugin that auto-closes, deletes and skips over matching delimiters in zsh intelligently. Hopefully.
# NOTE: This should always come last (even after zsh-completions).
zinit wait'1' for hlissner/zsh-autopair

# Sets the prompt theme. The shell is fully set up at this point.
#
# Also suppress warnings.
# See: https://github.com/zdharma/zinit/issues/406
eval "$(starship init zsh)" >/dev/null 2>&1
