# ~/.zshrc: Sourced by ZSH(1) in interactive shells. It should contain commands
# to set up aliases, functions, options, key bindings, etc.
#
# TODO: Continue to implement usefullness starting with:
# https://github.com/unixorn/awesome-zsh-plugins#completions

# Installs antibody if it doesn't exist.
[[ ! -f ${HOME}/.local/bin/antibody ]] && curl -sfL https://install.goreleaser.com/github.com/getantibody/antibody.sh | sh -s -- -b ${HOME}/.local/bin

# Set $PATH so it includes user's private binaries if it exists.
[[ -d ~/bin ]] && PATH="$HOME/bin:$PATH"
[[ -d ~/.local/bin ]] && PATH="$HOME/.local/bin:$PATH"

# Add Linuxbrew to $PATH if it's installed.
[[ -d /home/linuxbrew/.linuxbrew ]] && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

# Sets the directory of globally installed npm packages to the users $HOME and
# add it to $PATH, avoiding EACCES errors. Only if npm is installed.
(( $+commands[npm] )) && export NPM_CONFIG_PREFIX="$HOME/.npm-global"
(( $+commands[npm] )) && PATH="$HOME/.npm-global/bin:$PATH"

# Colored GCC warnings and errors.
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# make less more friendly for non-text input files, see lesspipe(1).
[[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"

# Enable color support for dircolors.
[[ -f ~/.dircolors ]] && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"

# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>
#
# Enable colorized long listing with human-readable size and ISO-8601 date 
# format.
alias ls='LC_COLLATE=C ls -lAh --color=auto --time-style="+%Y-%m-%d +%H:%M:%S" --group-directories-first'

# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>
#
# List in raw format with one entry per line.
alias lsraw='LC_COLLATE=C \ls -N1 --group-directories-first'

# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>
#
# Enable unified diff format by default.
alias diff='diff -u'

# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>
#
# Disable wget log file
alias wget='wget --hsts-file='

# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>
#
# Shorthand for alias to
#
# * Only display ANSI "color" escape sequences in "raw" form.
#   (-R, --RAW-CONTROL-CHARS)
# * Automatically exit if the entire file can be displayed on the first screen.
#   (-F, --quit-if-one-screen)
# * Disable sending the termcap (de)initialization strings to the terminal to
#   avoid unnecessary operations like clearing the screen. (-X, --no-init)
# * Use two tab stops. (-x2, --tabs=n)
alias less='less -RFXx2'

# Shorthand for alias to
#
# * Prompt before overwriting files. (-i, --interactive)
# * Preserve: mode, ownership and timestamps. (-p)
# * Explain what operations are being done. (-v, --verbose)
alias cp='cp -ipv'

# Shorthand for alias to
#
# * Prompt before overwriting files. (-i, --interactive
# * Move only when the SOURCE file is newer than the destination file or when
#   the destination file is missing. (-u, --update)
# * Explain what operations are being done. (-v, --verbose)
alias mv='mv -iuv'

# Shorthand for alias to
#
# * Prompt once before removing more than three files, or when removing
#   recursively. (-i)
# * Explain what operations are being done. (-v, --verbose)
alias rm='rm -Iv'

# Create a new directory and enter it.
#
# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>
#
# @param $1 the name of the directory to create and enter
mkd() {
  mkdir -p "$@" && cd "$@"
}

# Starts Antibody.
source <(antibody init)

# Only bundled if an external program is installed.
(( $+commands[adb] )) && antibody bundle robbyrussell/oh-my-zsh path:plugins/adb kind:fpath || echo 'adb is not installed or not located in $PATH.'
(( $+commands[http] )) && antibody bundle robbyrussell/oh-my-zsh path:plugins/httpie kind:fpath || echo 'httpie is not installed or not located in $PATH.'
(( $+commands[xclip] )) && antibody bundle zpm-zsh/clipboard || echo 'xclip is not installed or not located in $PATH.'

# Only bundled if a file is present.
[[ -f /usr/lib/command-not-found ]] && antibody bundle sorin-ionescu/prezto path:modules/command-not-found
[[ -f ~/.gitconfig ]] && antibody bundle zdharma/zsh-diff-so-fancy

# Only bundled if a directory is present.
[[ -d /home/linuxbrew/.linuxbrew ]] && antibody bundle Homebrew/brew path:completions/zsh kind:fpath

antibody bundle yous/vanilli.sh
antibody bundle MichaelAquilina/zsh-you-should-use
antibody bundle sorin-ionescu/prezto path:modules/archive/functions kind:path
antibody bundle sorin-ionescu/prezto path:modules/archive/functions kind:fpath
antibody bundle zpm-zsh/colors
antibody bundle zdharma/fast-syntax-highlighting
antibody bundle robbyrussell/oh-my-zsh path:plugins/colored-man-pages
antibody bundle robbyrussell/oh-my-zsh path:plugins/transfer
antibody bundle zsh-users/zsh-autosuggestions
antibody bundle zsh-users/zsh-completions
antibody bundle zsh-users/zsh-history-substring-search

# Change it according to your up/down arrow keys.
# To see if they match with your keyboard, run cat -v and observe it's output.
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main pattern)
ZSH_HIGHLIGHT_PATTERNS+=("rm *" "fg=white,bold,bg=red")

ZSH_AUTOSUGGEST_USE_ASYNC=true

# Binds the "Ctrl + Space" to fetch a command autosuggestion.
bindkey '^ ' autosuggest-fetch

# Binds the "Ctrl + ->" to accept the command autosuggestion.
bindkey '^[[1;5C' autosuggest-accept

# Initializes ZSH's completion engine
autoload -U compinit && compinit

# Using the "pure" prompt, made by Sindre Sorhus.
antibody bundle mafredri/zsh-async
antibody bundle sindresorhus/pure
