[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer, the value of this option is a string.
  colorscheme = "nord"
  colorscheme_bg = "dark"

  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors, the type of the value is boolean, true or false.
  enable_guicolors = true

  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "nil"
  statusline_iseparator = "bar"
  buffer_index_type = 4
  windows_index_type = 3

  # Display file type icon on the tabline, If you do not have nerd fonts
  # installed, please change the value to false
  enable_tabline_filetype_icon = true

  # Display current mode text on statusline, by default It is disabled,
  # only color will be changed when switch modes.
  enable_statusline_mode = false
  statusline_unicode_symbols = false

  # Enable vim compatible mode, avoid changing origin vim key bindings
  vimcompatible = true

[[layers]]
  name = "autocomplete"
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "cycle"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "format"

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"
  git_plugin = "fugitive"

[[layers]]
  name = "sudo"

[[layers]]
  name = "treesitter"

[[layers]]
  name = "ui"
  enable_sidebar = true
  enable_scrollbar = true
  enable_indentline = true
  enable_cursorword = true
  indentline_char = "|"
  conceallevel = 0
  concealcursor = ""
  cursorword_delay = 50
  cursorword_exclude_filetype = []
  indentline_exclude_filetype = []

[[layers]]
  name = "VersionControl"
