tap "beeftornado/rmtree"
tap "clementtsang/bottom"
tap "github/gh"
tap "rs/tap"

# These programs need to be built from source since their last release was ages ago.
brew "rust", link: false
brew "exa"#, args:["HEAD"]
brew "ripgrep"#, args:["HEAD"]

brew "bat"
brew "bottom"
brew "fd"
brew "fzf"
brew "gh"
brew "git-crypt"
brew "git-delta"
brew "httpie"
brew "procs"
brew "rm-improved"
brew "starship"
