# See: https://mise.jdx.dev/configuration.html
[tools]
bun = "latest"
node = "lts"
python = "{{ get_env(name='PYTHON_VERSION', default='latest') }}"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
python.compile = true
python.uv_venv_auto = true
python.uv_venv_create_args = ["--seed"]
