hotkeys:
  profile: {}
  shell: {}
terminal:
  colorScheme: &ref_0
    name: Nord
    foreground: '#D8DEE9'
    background: '#2E3440'
    cursor: '#D8DEE9'
    colors:
      - '#3B4252'
      - '#BF616A'
      - '#A3BE8C'
      - '#EBCB8B'
      - '#81A1C1'
      - '#B48EAD'
      - '#88C0D0'
      - '#E5E9F0'
      - '#4C566A'
      - '#BF616A'
      - '#A3BE8C'
      - '#EBCB8B'
      - '#81A1C1'
      - '#B48EAD'
      - '#8FBCBB'
      - '#ECEFF4'
  frontend: xterm-webgl
  font: Iosevka Regular
  ligatures: true
  background: theme
  fallbackFont: ''
  customColorSchemes:
    - *ref_0
  environment: {}
  profile: wsl-ubuntu
ssh: {}
appearance:
  vibrancy: false
  vibrancyType: fluent
  theme: Standard
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - community-color-schemes
  - ssh
