# ~/.zshenv: Sourced on ALL invocations of ZSH(1), unless the -f option is
# set.
#
# NOTE: It should NOT normally contain commands to set the command search path,
# or other common environment variables unless you really know what you're
# doing. E.g. running "PATH=/custom/path gdb program" sources this file (when
# gdb runs the program via $SHELL), so you want to be sure not to override a
# custom environment in such cases.  Note also that .zshenv should not contain
# commands that produce output or assume the shell is attached to a tty.
#
export ZSH_HOME="${ZDOTDIR:-${HOME}}"

export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export LANG="pt_BR.UTF-8"
export LC_ALL="pt_BR.UTF-8"
export LC_COLLATE="pt_BR.UTF-8"
export LC_CTYPE="pt_BR.UTF-8"
export LC_MESSAGES="pt_BR.UTF-8"
export LC_MONETARY="pt_BR.UTF-8"
export LC_NUMERIC="pt_BR.UTF-8"
export LC_TIME="pt_BR.UTF-8"

case "$OSTYPE" in
  darwin*)
    [[ -d "$HOME/Library/Android/sdk" ]] && export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
    [[ -d "$HOME/Library/Android/sdk/build-tools" ]] && export PATH="$HOME/Library/Android/sdk/build-tools:$PATH"
    [[ -d "$HOME/Library/Android/sdk/platform-tools" ]] && export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"
    [[ -d "/usr/local/sbin" ]] && export PATH="/usr/local/sbin:$PATH"

    [ ! -f "$ZSH_HOME/.iterm2_shell_integration.zsh" ] && curl -L "https://iterm2.com/shell_integration/zsh" -o "$ZSH_HOME/.iterm2_shell_integration.zsh"
    source "$ZSH_HOME/.iterm2_shell_integration.zsh"

    export NVM_DIR="$ZSH_HOME/.nvm"
    [[ ! -d "$NVM_DIR" ]] && mkdir "$NVM_DIR"
    source "/usr/local/opt/nvm/nvm.sh"
    source "/usr/local/opt/nvm/etc/bash_completion.d/nvm"

    alias cp="cp -ipv"
    alias diff="diff -u"
    alias mv="mv -iv"
    alias rm="rm -iv"

    alias emulator="$HOME/Library/Android/sdk/emulator/emulator -avd Pixel_3_API_29 &"
    alias qba="cd $HOME/WorkDir/quero/qb_app_rn"
    alias quero="cd $HOME/WorkDir/quero"
    alias screenrecord="xcrun simctl io booted recordVideo "Record from $(date).gif""
  ;;
esac

source "$HOME/.ztoken"
