# ~/.zshrc: Sourced by ZSH(1) in interactive shells. It should contain commands
# to set up aliases, functions, options, key bindings, etc.
#
# TODO: Continue to implement usefullness starting with:
# https://github.com/unixorn/awesome-zsh-plugins#completions

# Setup iTerm2 shell integration.
# shellcheck disable=SC1090
source "$HOME/.iterm2_shell_integration.zsh"

# Setup Homebrew's ZSH completions.
FPATH="/usr/local/share/zsh/site-functions:$FPATH"

#
# $PATH additions.
#
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/Library/Android/sdk/build-tools:$PATH"
export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"

#
# Node Version Manager.
#
[[ ! -d "$HOME/.nvm" ]] && mkdir "$HOME/.nvm"
# shellcheck disable=SC1091
source "/usr/local/opt/nvm/nvm.sh"
# shellcheck disable=SC1091
source "/usr/local/opt/nvm/etc/bash_completion.d/nvm"

# Create a new directory and enter it.
#
# @param $1 the name of the directory to create and enter
mkd() {
  mkdir -p "$@" && cd "$@" || return
}

# shellcheck disable=SC1090
source <(antibody init)

export YSU_MODE=ALL
export YSU_HARDCORE=1

export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main pattern)
export ZSH_HIGHLIGHT_PATTERNS=("rm *" "fg=white,bold,bg=red")

export ZSH_AUTOSUGGEST_USE_ASYNC=true

antibody bundle ael-code/zsh-colored-man-pages
antibody bundle chrissicool/zsh-256color
antibody bundle DarrinTisdale/zsh-aliases-exa
antibody bundle hlissner/zsh-autopair
antibody bundle MichaelAquilina/zsh-you-should-use
antibody bundle mroth/evalcache
antibody bundle rapgenic/zsh-git-complete-urls
antibody bundle willghatch/zsh-saneopt
antibody bundle yous/vanilli.sh
antibody bundle zdharma/fast-syntax-highlighting
antibody bundle zigius/expand-ealias.plugin.zsh
antibody bundle zpm-zsh/colorize
antibody bundle zsh-users/zsh-autosuggestions
antibody bundle zsh-users/zsh-completions
antibody bundle zsh-users/zsh-history-substring-search

# Change it according to your up/down arrow keys.
# To see if they match with your keyboard, run cat -v and observe it's output.
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Binds the "Ctrl + Space" to fetch a command autosuggestion.
bindkey '^ ' autosuggest-fetch

# Binds the "Ctrl + ->" to accept the command autosuggestion.
bindkey '^[[1;5C' autosuggest-accept

autoload -U compinit && compinit

_evalcache brew command-not-found-init

# Starts Android Emulator from the shell.
# TODO: Add a dynamic way of loading the emulator.
alias emulator='$HOME/Library/Android/sdk/emulator/emulator -avd Pixel_3_API_29 &'

#
# Easy directory navigation.
#
alias wd='cd $HOME/WorkDir || return '
alias dotfiles='cd $HOME/WorkDir/dotfiles || return '
alias qb='cd $HOME/WorkDir/qb_app_rn || return '
alias qba='cd $HOME/WorkDir/qb_app_rn/app || return '
alias qbs='cd $HOME/WorkDir/qb_app_rn/server || return '

# * Only display ANSI "color" escape sequences in "raw" form.
#   (-R, --RAW-CONTROL-CHARS)
# * Automatically exit if the entire file can be displayed on the first screen.
#   (-F, --quit-if-one-screen)
# * Disable sending the termcap (de)initialization strings to the terminal to
#   avoid unnecessary operations like clearing the screen. (-X, --no-init)
# * Use two tab stops. (-x2, --tabs=n)
alias less='less -RFXx2'

# Enable unified diff format by default.
ealias diff='diff -u'

# Use RFC 5322 date format by default.
alias date='date -R'

# * Prompt before overwriting files. (-i, --interactive)
# * Preserve: mode, ownership and timestamps. (-p)
# * Explain what operations are being done. (-v, --verbose)
ealias cp='cp -ipv'

# * Prompt before overwriting files. (-i, --interactive
# * Move only when the SOURCE file is newer than the destination file or when
#   the destination file is missing. (-u, --update)
# * Explain what operations are being done. (-v, --verbose)
ealias mv='mv -iuv'

# * Prompt once before removing more than three files, or when removing
#   recursively. (-i)
# * Explain what operations are being done. (-v, --verbose)
ealias rm='rm -iv'

# Prompt setup
antibody bundle mafredri/zsh-async
antibody bundle sindresorhus/pure