# ~/.zshrc: Sourced by ZSH(1) in interactive shells. It should contain commands
# to set up aliases, functions, options, key bindings, etc.
#
export ZIM_HOME="$ZSH_HOME/.zim"

[[ -d "$HOME/bin" ]] && export PATH="$HOME/bin:$PATH"

[[ ! -d "${ZIM_HOME}" ]] && git clone --branch develop git@github.com:zimfw/zimfw.git "${ZIM_HOME}"
[[ -s ${ZIM_HOME}/zimfw.zsh ]] && source ${ZIM_HOME}/zimfw.zsh

alias less="less -RFXx2"

alias dotfiles="cd $HOME/WorkDir/dotfiles"
alias wd="cd $HOME/WorkDir"
